import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://provider.nha.gov.in/")
    page.get_by_role("textbox", name="Captcha").click()
    page.get_by_role("textbox", name="Captcha").press("CapsLock")
    page.get_by_role("textbox", name="Captcha").fill("7RYKYX")
    page.get_by_role("textbox", name="Registered Mobile No/User ID").click()
    page.get_by_role("textbox", name="Registered Mobile No/User ID").click()
    page.get_by_role("textbox", name="Registered Mobile No/User ID").fill("dineshdwarka")
    page.get_by_text("verify").click()
    page.get_by_role("spinbutton", name="OTP").click()
    page.locator(".css-ackcql").click()
    page.locator(".css-ackcql").click()
    page.get_by_role("spinbutton", name="OTP").click()
    page.get_by_role("spinbutton", name="OTP").click()
    page.get_by_role("spinbutton", name="OTP").fill("324964")
    page.get_by_role("textbox", name="Enter the Captcha").click()
    page.get_by_role("textbox", name="Enter the Captcha").press("CapsLock")
    page.get_by_role("textbox", name="Enter the Captcha").fill("P73E8A")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="CLOSE").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("1015795522")
    page.locator(".icon").click()
    page.locator("#Path_98789").click()
    page.get_by_role("button", name="Medical Information").click()
    page.get_by_role("button", name="Edit").click()
    page.locator("div:nth-child(2) > .formgroup > div > .cCymtLXWl0AEQgHDm9r_ > .X822VFjKSr1jqv5N60Yx").first.click()
    page.locator("div:nth-child(2) > .formgroup > div:nth-child(3) > .cCymtLXWl0AEQgHDm9r_ > .X822VFjKSr1jqv5N60Yx").click()
    page.locator(".X822VFjKSr1jqv5N60Yx").first.click()
    page.locator("div:nth-child(3) > .cCymtLXWl0AEQgHDm9r_ > .X822VFjKSr1jqv5N60Yx").first.click()
    page.get_by_role("button", name="Personal History").click()
    page.get_by_role("button", name="General Findings").click()
    page.get_by_role("button", name="General Findings").click()
    page.get_by_role("button", name="General Findings").click()
    page.get_by_role("button", name="Edit").click()
    page.get_by_text("No", exact=True).nth(2).click()
    page.get_by_text("Yes").nth(2).click()
    page.locator("div:nth-child(6) > .formgroup > div:nth-child(3) > .cCymtLXWl0AEQgHDm9r_ > .X822VFjKSr1jqv5N60Yx").click()
    page.get_by_role("button", name="SAVE").click()
    page.get_by_role("button", name="Family History").click()
    page.get_by_role("button", name="SAVE").click()
    page.get_by_role("button", name="SAVE").click()
    page.locator("[id=\"Heart Disease\"] > .css-1bzqg8e-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-8mmkcg").click()
    page.get_by_role("button", name="Family History").click()
    page.get_by_role("button", name="Admission Information").click()
    page.get_by_role("button", name="Admission Details").click()
    page.get_by_role("button", name="Edit").click()
    page.locator("div:nth-child(2) > div:nth-child(2) > .formgroup > .j7C3UwF5uW799zPnTxod > .mr-2 > svg").click()
    page.get_by_role("button", name="Select Sunday, December 28,").click()
    page.locator("div:nth-child(3) > .formgroup > div > .cCymtLXWl0AEQgHDm9r_").first.click()
    page.locator("div:nth-child(3) > .formgroup > div:nth-child(3) > .cCymtLXWl0AEQgHDm9r_ > .X822VFjKSr1jqv5N60Yx").click()
    page.locator("#AdmissionType > .css-1bzqg8e-control > .css-14ntbqx > .css-ackcql").click()
    page.locator("#react-select-37-option-0").click()
    page.get_by_role("button", name="SAVE").click()
    page.get_by_role("button", name="Treatment").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page.locator("[id=\"1001\"]").check()
    page.locator("[id=\"1002\"]").check()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(2).click()
    page.get_by_role("textbox", name="Enter Diagnosis").click()
    page.get_by_role("textbox", name="Enter Diagnosis").click()
    page.get_by_role("textbox", name="Enter Diagnosis").fill("xra")
    page.get_by_role("textbox", name="Enter Diagnosis").click()
    page.get_by_role("textbox", name="Enter Diagnosis").fill("")
    page.get_by_role("textbox", name="Enter Diagnosis").press("CapsLock")
    page.get_by_role("textbox", name="Enter Diagnosis").fill("X ray")
    page.get_by_text("Radiological examination").click()
    page.locator("div").filter(has_text=re.compile(r"^Secondary$")).click()
    page.get_by_role("radio", name="Manual Primary").check()
    page.get_by_role("button", name="ADD").click()
    page.locator("tr:nth-child(2) > td:nth-child(5) > .w4AeFazhPeXP69wp9yWQ").click()
    page.get_by_role("button", name="YES").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(3).click()
    page.locator(".col-lg-10 > .formgroup > .css-b62m3t-container > .css-1bzqg8e-control").first.click()
    page.get_by_text("Behavioural Therapy", exact=True).click()
    page.locator(".col-lg-10 > .formgroup > .css-b62m3t-container > .css-1bzqg8e-control > .css-14ntbqx > .css-ackcql").click()
    page.locator("#react-select-7-option-0").click()
    page.get_by_role("textbox", name="Type here", exact=True).click()
    page.get_by_role("textbox", name="Type here", exact=True).fill("2")
    page.locator(".m9FzljqXbDJyFhzambbf").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(4).click()
    page.locator(".LFutEuy0mRc5Jk00fBkR").first.click()
    page.get_by_role("button", name="Drag your file here  Or").click()
    page.get_by_role("button", name="Drag your file here  Or").set_input_files("NSCR78356.pdf")
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(5).click()
    page.locator(".my-auto > div > .css-b62m3t-container > .css-1bzqg8e-control > .css-14ntbqx > .css-ackcql").click()
    page.get_by_text("Other", exact=True).click()
    page.get_by_role("textbox", name="Doctor's Name").click()
    page.get_by_role("textbox", name="Doctor's Name").press("CapsLock")
    page.get_by_role("textbox", name="Doctor's Name").fill("test")
    page.get_by_role("textbox", name="Registration ID / HPR ID").click()
    page.get_by_role("textbox", name="Registration ID / HPR ID").fill("444")
    page.locator("#qualification > .css-1bzqg8e-control > .css-14ntbqx > .css-ackcql").click()
    page.get_by_text("M.D.", exact=True).click()
    page.get_by_role("textbox", name="Contact No.").click()
    page.locator("#qualification > .css-1bzqg8e-control > .css-1wy0on6 > div > .css-8mmkcg").first.click()
    page.locator(".css-1gtu0rj-indicatorContainer > .css-8mmkcg > path").click()
    page.locator(".css-1gtu0rj-indicatorContainer > .css-8mmkcg > path").click()
    page.locator(".css-1gtu0rj-indicatorContainer > .css-8mmkcg").click()
    page.locator("#react-select-48-option-0").click()
    page.get_by_role("textbox", name="Contact No.").click()
    page.get_by_role("textbox", name="Contact No.").fill("1234567899")
    page.get_by_role("textbox", name="Contact No.").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Contact No.").fill("6789067890")
    page.get_by_role("textbox", name="Contact No.").click()
    page.get_by_role("button", name="ADD").nth(2).click()
    page.get_by_role("button", name="Preview & Validate").click()
    page.get_by_text("No of Days/Units").nth(2).click()
    page.locator("div").filter(has_text="validate EDIT").nth(3).click()
    page.locator("div").filter(has_text="validate EDIT").nth(3).click()
    page.get_by_role("button", name="validate", exact=True).click()
    page.locator("div").filter(has_text="Initiate Pre-Authorization").nth(3).click()
    page.locator("div").filter(has_text="Initiate Pre-Authorization").nth(3).click()
    page.get_by_text("Preview").nth(2).click()
    page.get_by_role("button", name="EDIT").click()
    page.get_by_role("button", name="Home").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("1015795522")
    page.locator(".icon").click()
    page.locator("#Path_98789").click()
    page.locator("div").filter(has_text="HomePre-Authorization (").nth(3).click()
    page.get_by_role("button", name="Dinesh Kumar Sharma").click()
    page.get_by_role("button", name="Logout").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
